"""Chapter 4 adaptive inference gateway public API."""

from policyops.inference.fixtures import (
    EXPECTED_RISK_COUNTS,
    EXPECTED_SUITE_COUNTS,
    EVALS_CASES_ROOT,
    FixtureLoadError,
    load_and_validate_cases,
    load_gateway_workload,
)
from policyops.inference.gateway import (
    AdaptiveInferenceGateway,
    GatewayClock,
    ResponseCache,
    benchmark_gateway,
    fixture_profiles,
    hard_gate,
    quality_gate,
    run_gateway_verification,
)
from policyops.inference.route_policy import RouteProfile, route_profiles
from policyops.inference.schemas import (
    BenchmarkReport,
    BenchmarkRow,
    CacheEntry,
    CacheKey,
    CandidateResult,
    FailureReason,
    GatewayResult,
    InferenceBudget,
    InferenceRequest,
    MatchedPairComparison,
    MatchedPairOutcome,
    ModelProfile,
    ProfileAggregate,
    ReasoningEffort,
    RiskTier,
    TaskClass,
    VerificationResult,
)

__all__ = [
    "AdaptiveInferenceGateway",
    "BenchmarkReport",
    "BenchmarkRow",
    "CacheEntry",
    "CacheKey",
    "CandidateResult",
    "EVALS_CASES_ROOT",
    "EXPECTED_RISK_COUNTS",
    "EXPECTED_SUITE_COUNTS",
    "FailureReason",
    "FixtureLoadError",
    "GatewayClock",
    "GatewayResult",
    "InferenceBudget",
    "InferenceRequest",
    "MatchedPairComparison",
    "MatchedPairOutcome",
    "ModelProfile",
    "ProfileAggregate",
    "ReasoningEffort",
    "ResponseCache",
    "RiskTier",
    "RouteProfile",
    "TaskClass",
    "VerificationResult",
    "benchmark_gateway",
    "fixture_profiles",
    "hard_gate",
    "load_and_validate_cases",
    "load_gateway_workload",
    "quality_gate",
    "route_profiles",
    "run_gateway_verification",
]
